
server:
  port: 8902
spring:
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: classpath:/templates/
      suffix: .html
  freemarker:
    template-loader-path: classpath:/templates/
    suffix: .ftl
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
